### ISSUE TITLE
Installation fails with download error

### ISSUE THREAD

**Issue by lenscritic** [dylanonelson/sn-scratch-editor#27]
In the Standard Notes web app, if I do "Import Extension" and then paste in the follow url:
 `https://scratch-editor.com/ext.json`
this error text is presented:
 `Error downloading package details. Please check the Extension Link and try again.`

I've tried multiple times over the last 12 hours but always get the same error. All other extensions that I've tried install without issue (eg. Nimble Editor, Rich Markdown Editor). Not sure it matters, but I'm using the free version of Standard Notes.

I have verified that I can view the json contents without issue by putting the url in Chrome. Also if I try the download_url instead (mentioned in json), the .zip file downloads without issue,

OS: Windows 10 Pro (up to date)
Browser: Chrome version 95.0.4638.69 (Official Build) (64-bit)

**Comment by dylanonelson** [comment]
Hey @lenscritic, thank you for opening an issue! I think I know what the problem is, but it will take me a couple days to fix it. I will respond with an update once I have some time.

In the meantime, just in case you didn’t realize, the extension installs fine on the desktop app for me.

**Comment by dylanonelson** [comment]
I believe I have fixed this issue but I can’t verify it because the extensions menu seems to be missing from my Standard Notes app, on both web and desktop. I think others are having the same issue but I’m not sure how widespread it is: https://www.reddit.com/r/StandardNotes/comments/qt6icr/missing_extensions_menu/.

I’ll keep an eye on this and close the issue once I can verify that it’s resolved.

**Comment by lenscritic** [comment]
Thanks for the follow-up!

To attempt an extension install, it looks like you now need to select the preferences icon -> "General" tab, and then expand the "Advanced Settings" area. There you should find "Install Custom Extension".

I tried using this url: https://scratch-editor.com/ext.json
After confirming that I want to install from an untrusted source I still get the "Error downloading package details. Please check the extension link and try again." error.

**Comment by dylanonelson** [comment]
Yes, I finally figured this out myself just now, thanks. I had to make one more adjustment to the editor server, but now it is working for me via the web interface. I believe that 'untrusted source' dialog is outside my control unfortunately, but I will look into it.

**Comment by lenscritic** [comment]
Works great now, thanks Dylan!

**Comment by lenscritic** [comment]
Hi, unfortunately this issue appears to be happening again. I was having some issues with Scratch so I tried removing it and re-installing, but it won't let me install. I get the same "Error downloading package details. Please check the extension link and try again." error.

I'm using this url : https://scratch-editor.com/ext.json
which returns valid json in my web browser, but doing a "Install Custom Plugin" with that url in Standard Notes (web version) returns the error.

**Comment by dylanonelson** [comment]
Hey, I am taking a look. I see the issue as well. Right now it looks like this may be out of my control (i.e., a config on the Standard Notes side). If you use a different url (https://raw.githubusercontent.com/dylanonelson/sn-scratch-editor/latest/dist/ext.json) the request makes it past the CSP but fails with a different access control error.

I will post about this in the SN forum. In the meantime, you should be able to install the extension from one of the other Standard Notes clients. Once you get it installed in one, it will work everywhere. 

Documentation for others and myself:

Trying to install with https://scratch-editor.com/ext.json yields `Connecting to 'https://scratch-editor.com/ext.json' violates the following Content Security Policy directive: "connect-src api.standardnotes.com assets.standardnotes.com sync.standardnotes.org files.standardnotes.com ws://sockets.standardnotes.com raw.githubusercontent.com listed.to blob:". The action has been blocked.`

Trying to install with https://raw.githubusercontent.com/dylanonelson/sn-scratch-editor/latest/dist/ext.json yields `Access to fetch at 'https://raw.githubusercontent.com/dylanonelson/sn-scratch-editor/latest/dist/ext.json' from origin 'https://app.standardnotes.com' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.`

One solution would seem to be changing the Access-Control-Allow-Origin header from `*` to list the actual Standard Notes origins, but I'm not sure what the right origin is for the mobile apps or for other potential clients, and it seems brittle. Also, it seems like the GitHub url is supposed to work but does not because of code in the SN web app; if so, it's simply a bug.

**Comment by lenscritic** [comment]
Thanks for looking into it and providing the workaround suggestion. I was able to get it installed by using the mobile app.
