### ISSUE TITLE
Dark theme = unreadable text (Mobile app)

### ISSUE THREAD

**Issue by javaskript** [dylanonelson/sn-scratch-editor#62]
In the iOS mobile app, having the Standard Notes appearance set to Dark or Carbon, etc, leads to black, illegible text in a Scratch Editor note. Text should be white when the background is dark.

**Comment by dylanonelson** [comment]
Hey there, thanks for creating an issue! This should be an easy fix. I implemented some theming support originally but I don't use dark mode so I never noticed the bug. I will take a look within the next week and hopefully push something out.

**Comment by dylanonelson** [comment]
This is now fixed. Please let me know if there are other theme compatibility issues that crop up.

**Comment by javaskript** [comment]
> Android user here. To me the appereance is still the same. See the screenshot: https://i.imgur.com/d8G5lPm.png
> 
> Seems the update is not taking place.

It was working for me on mobile iOS but now looks like yours too.

Desktop also looks like this for me: https://i.imgur.com/d4dDAmt.jpeg

I thought it may be that the old plugin is cached in Standard Notes but a complete reinstall of both the mobile and desktop apps still results in the same

**Comment by dylanonelson** [comment]
I took a look at the theming issue. This seems to be a bug in Standard Notes unfortunately. I will see if I can get some help from their team. The good news is that there is a workaround.

The problem is that the built-in theme stylesheet is loaded as a file locally on mobile, and the editor plugin web view is not allowed to load local files. I can't change how the theme stylesheet is loaded. The built-in themes seem to me to be in a broken state for editor plugins. I am not sure if this is a recent change—maybe it was, since @javaskript you say it was working for you briefly?

The workaround is to use a custom theme like https://draculatheme.com/standard-notes. These themes work fine with Scratch because their stylesheets are loaded from a url. The themes that come with Standard Notes do not work with Scratch.

> Desktop also looks like this for me: https://i.imgur.com/d4dDAmt.jpeg

@javaskript this may be a caching or network issue, since I can't reproduce this. It looks like the stylesheet is not loading for you for some reason. If this is a persistent problem, could you open a separate issue? Thanks.

**Comment by dylanonelson** [comment]
Closing this since it is fixed for me. Thanks for the issue and let me know if it's still a problem.

**Comment by javaskript** [comment]
> [@javaskript](https://github.com/javaskript) this may be a caching or network issue, since I can't reproduce this. It looks like the stylesheet is not loading for you for some reason. If this is a persistent problem, could you open a separate issue? Thanks.

Still happening for some reason. I tried:

- Fully uninstalling Standard Notes and all plugins, using Revo Installer for a deep cleanup of the entire filesystem and registry.
- Making a new Standard Note account, and trying an offline/self-hosted account as well.
- Various Windows and macOS desktops/laptops, both on my home network and work network.
- Swapping DNS between Cloudflare, Google, and my ISP.
- Clearing Windows and macOS DNS cache
- I actually just had my ISP changed too, and it still [looks like this](https://i.imgur.com/d4dDAmt.jpeg) when I install Scratch on a clean install of Standard Notes.
- Went nuclear and even installed a fresh copy of Windows and macOS, same thing.

For some reason, no matter what I've tried over the past 5 months, I cannot get Scratch Editor working since Release 0.0.48 in October.

**Comment by dylanonelson** [comment]
Hey, I will take a closer look at this, but it might take me a bit since I am busy with other things at the moment. Last time I tried I could not reproduce the issue, and everything still seems to be working fine on my end. Could you let me know a few things when you have a chance?

- the Standard Notes version (or one of them at least) where it doesn't work
- a list of platforms where it doesn't work (it sounds like you're trying to install it on a Mac desktop and Windows desktop, at least)

Thanks for responding on this thread. I will try installing fresh on another device and see if that works for me.

**Comment by javaskript** [comment]
> Hey, I will take a closer look at this, but it might take me a bit since I am busy with other things at the moment. Last time I tried I could not reproduce the issue, and everything still seems to be working fine on my end. Could you let me know a few things when you have a chance?
> 
> - the Standard Notes version (or one of them at least) where it doesn't work
> - a list of platforms where it doesn't work (it sounds like you're trying to install it on a Mac desktop and Windows desktop, at least)
> 
> Thanks for responding on this thread. I will try installing fresh on another device and see if that works for me.

No worries take as long as you need. I'm sure the issue may be on my end, but I've just exhausted all possible solutions I could think of over these past months so commented back here as a last resort.

Scratch works perfectly across all mobile apps, on my iPhone (iOS 26.4) and Android (Android 16). The issue only occurs on my:
Windows 11 desktop & laptop
Mac desktop and MacBook (macOS 26.4)

All devices are running the latest Standard Notes v3.201.21. Complete app and OS reinstalls, modem and router swapped, ISP changed, DNS providers switched between Google/Cloudflare/AdGuard. All of the other above attempts too, and no dice. I'm stumped!

Thanks for looking into it, let me know if you'd like me to open this under a new issue.
